import type React from "react";
import type { Metadata } from "next";
import { Toaster } from "sonner";
import { Suspense } from "react";
import "./globals.css";

export const metadata: Metadata = {
	title: "Pert analysis app",
	description: "Created to display the results of a PERT analysis and manage tasks",
	generator: "Pert analysis app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`font-sans antialiased`}
			>
				<Suspense fallback={null}>{children}</Suspense>
				<Toaster position="top-right" richColors />
			</body>
		</html>
	);
}

// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
